# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=portfolio.models.item_upload_to)),
                ('category', models.ManyToManyField(to='portfolio.Category')),
                ('results', models.ManyToManyField(to='portfolio.Result')),
                ('slider', models.ManyToManyField(to='portfolio.Slider')),
            ],
            options={
                'verbose_name': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f',
                'verbose_name_plural': '\u0413\u0430\u043b\u0435\u0440\u0435\u044f',
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='results',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='slider',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
