# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170726_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '\u041f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e', 'verbose_name_plural': '\u041f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e'},
        ),
    ]
